# Generated by Django 4.0.3 on 2024-01-12 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_conference_temp_conference_weather_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conference',
            old_name='temp',
            new_name='weather_temp',
        ),
    ]
