# Generated by Django 4.0.3 on 2024-01-12 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_temp_conference_weather_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='weather_description',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='weather_temp',
            field=models.URLField(null=True),
        ),
    ]
