# Generated by Django 4.0.3 on 2024-01-12 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_conference_weather_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='weather_description',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='weather_temp',
        ),
    ]
